#!/bin/bash
#SBATCH --job-name=dgemm-naive
#SBATCH --output job-naive.stdout
#SBATCH --time=00:10:00
#SBATCH --partition=development
#SBATCH --account=TG-CCR140008
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
echo "Job Name (ID): "$SLURM_JOB_NAME" ("$SLURM_JOB_ID")"
echo "Working directory: "$SLURM_SUBMIT_DIR
./benchmark-naive